"use client";
import { Footer, Navbar } from "@/components/main";
import "./globals.css";
import { AuthContextProvider } from "@/context/authContext";
import MainLayout from "@/components/common/layout/MainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative bg-teal-50 overflow-x-hidden">
        <AuthContextProvider>
          <MainLayout>{children}</MainLayout>
        </AuthContextProvider>
      </body>
    </html>
  );
}
