"use client";

import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
import NavbarDashboard from "@/components/adminDashboard/NavbarDashboard";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by Admin Dashboard",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="grid grid-cols-8 px-5">
      <nav className="col-span-2">
        <NavbarDashboard />
      </nav>
      <div className="col-span-6 px-4">{children}</div>
    </section>
  );
}
